// ─── Dhikr Content Types ──────────────────────────────────────────────────────
// All types for the verified dhikr/dua content system.
// Content must come from verified sources — never generated by AI.

export type DhikrCategory =
  | "morning"
  | "evening"
  | "after_salah"
  | "general"
  | "sleep"
  | "protection"
  | "gratitude"
  | "forgiveness"
  | "ramadan"
  | "dua";

export type DhikrGrade =
  | "sahih"
  | "hasan"
  | "da'if"
  | "mutawatir"
  | "well_known"
  | "ungraded";

export interface CanonicalDhikr {
  id: string;
  arabic: string;
  transliteration?: string;
  translationEn: string;
  translationBn?: string;
  recommendedCount: number;
  category: DhikrCategory;
  source: string;
  reference: string;
  grade?: DhikrGrade;
  notes?: string;
}

export interface CanonicalDua {
  id: string;
  arabic: string;
  transliteration?: string;
  translationEn: string;
  translationBn?: string;
  category: DuaCategory;
  source: string;
  reference: string;
  grade?: DhikrGrade;
  notes?: string;
}

export type DuaCategory =
  | "morning"
  | "evening"
  | "sleep"
  | "travel"
  | "knowledge"
  | "forgiveness"
  | "protection"
  | "family"
  | "rizq"
  | "ramadan"
  | "general";

// ─── Session Types ────────────────────────────────────────────────────────────

export type DhikrSessionStatus = "COMPLETED" | "INTERRUPTED" | "CANCELLED";

export interface DhikrSession {
  id: string;
  userId: string;
  dhikrId: string;
  targetCount: number;
  completedCount: number;
  startedAt: string;
  completedAt?: string;
  status: DhikrSessionStatus;
  createdAt: string;
}

export interface DhikrFavorite {
  id: string;
  userId: string;
  dhikrId: string;
  createdAt: string;
}

// ─── Ramadan Types ────────────────────────────────────────────────────────────

export interface RamadanSettings {
  id: string;
  userId: string;
  isEnabled: boolean;
  suhoorReminder: boolean;
  iftarReminder: boolean;
  dailyQuranTarget: number; // minutes
  dhikrReminder: boolean;
  reflectionReminder: boolean;
  taraweehTracking: boolean;
  customChecklistItems: string[];
  createdAt: string;
  updatedAt: string;
}

export interface RamadanDailyLog {
  id: string;
  userId: string;
  hijriDate: string;
  ramadanDay: number;
  fajrCompleted: boolean;
  quranCompleted: boolean;
  morningAdhkarCompleted: boolean;
  dhikrCompleted: boolean;
  dhuhrCompleted: boolean;
  asrCompleted: boolean;
  iftarCompleted: boolean;
  maghribCompleted: boolean;
  eveningAdhkarCompleted: boolean;
  ishaCompleted: boolean;
  taraweehCompleted: boolean;
  reflectionCompleted: boolean;
  customItems: Record<string, boolean>;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface RamadanGoal {
  id: string;
  userId: string;
  title: string;
  description?: string;
  goalType: "quran_khatm" | "quran_daily" | "dhikr" | "adhkar" | "charity" | "reflection" | "custom";
  targetValue: number;
  currentValue: number;
  unit: string;
  startDate: string;
  targetDate?: string;
  isCompleted: boolean;
  createdAt: string;
  updatedAt: string;
}

// ─── Islamic Calendar Types ───────────────────────────────────────────────────

export interface HijriDate {
  year: number;
  month: number;
  day: number;
  monthName: string;
}

export interface RamadanInfo {
  isRamadan: boolean;
  ramadanDay?: number;
  totalDays: number;
  hijriDate: HijriDate;
}
